name: AWS EC2 Control
on:
  push:
    branches: [ main ]
  workflow_dispatch: # activate running manually

jobs:
  manage_aws:
    runs-on: self-hosted # run on my self hosted OCI instance
    steps:
      - name: Setup SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/login-key
          chmod 600 ~/.ssh/login-key

      - name: Start AWS Instance
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}
        run: |
          echo "Verifying state..."
          STATE=$(aws ec2 describe-instances --instance-ids "${{ secrets.AWS_EC2_INSTANCE_ID }}" --query "Reservations[0].Instances[0].State.Name" --output text)
          if [ "$STATE" = "stopped" ]; then
            aws ec2 start-instances --instance-ids "${{ secrets.AWS_EC2_INSTANCE_ID }}"
            aws ec2 wait instance-running --instance-ids "${{ secrets.AWS_EC2_INSTANCE_ID }}"
          fi

      - name: Run script on EC2 via SSH
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/login-key ubuntu@${{ secrets.AWS_EC2_PUBLIC_IP }} "cd ~/LinkMonitor && source venv/bin/activate && python link_monitor.py"

      - name: Stop the instance
        if: always() # stop it even if it gets errors
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}
        run: |
          aws ec2 stop-instances --instance-ids "${{ secrets.AWS_EC2_INSTANCE_ID }}"